# Generated by Django 4.2.16 on 2026-05-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('error', 'Error técnico')], default='pendiente', max_length=20)),
                ('modalidad', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Audio')], default='texto', max_length=10)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dim_claridad', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dim_coherencia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dim_precision', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dim_comunicacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dim_seguridad', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback_general', models.TextField(blank=True)),
                ('feedback_por_dimension', models.JSONField(default=dict)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista', to='candidatos.candidato')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
            options={
                'verbose_name': 'Entrevista IA',
                'db_table': 'entrevistas_ia',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado al candidato'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('expirado', 'Expirado')], default='generado', max_length=20)),
                ('duracion_minutos', models.IntegerField(default=45)),
                ('nota_maxima', models.IntegerField(default=20)),
                ('nota_minima', models.DecimalField(decimal_places=2, default=13.0, max_digits=4)),
                ('nota_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('feedback_ia', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_usado_min', models.IntegerField(blank=True, null=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='candidatos.candidato')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='vacantes.vacante')),
            ],
            options={
                'verbose_name': 'Examen',
                'db_table': 'examenes',
            },
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('categoria', models.CharField(help_text='Tecnología/habilidad que evalúa', max_length=100)),
                ('tipo', models.CharField(choices=[('multiple', 'Opción múltiple'), ('abierta', 'Pregunta abierta')], max_length=10)),
                ('enunciado', models.TextField()),
                ('puntos', models.IntegerField(default=2)),
                ('opcion_a', models.CharField(blank=True, max_length=500)),
                ('opcion_b', models.CharField(blank=True, max_length=500)),
                ('opcion_c', models.CharField(blank=True, max_length=500)),
                ('opcion_d', models.CharField(blank=True, max_length=500)),
                ('respuesta_correcta', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('respuesta_esperada', models.TextField(blank=True)),
                ('criterios_evaluacion', models.JSONField(default=list)),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.examen')),
            ],
            options={
                'db_table': 'preguntas_examen',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.CharField(blank=True, max_length=1)),
                ('respuesta_texto', models.TextField(blank=True)),
                ('es_correcta', models.BooleanField(blank=True, null=True)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback_ia', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='evaluaciones.preguntaexamen')),
            ],
            options={
                'db_table': 'respuestas_examen',
            },
        ),
        migrations.CreateModel(
            name='PreguntaEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('comportamental', 'Comportamental (STAR)'), ('situacional', 'Situacional')], max_length=20)),
                ('pregunta', models.TextField()),
                ('dimension_principal', models.CharField(blank=True, max_length=20)),
                ('respuesta_texto', models.TextField(blank=True)),
                ('audio_archivo', models.FileField(blank=True, null=True, upload_to='entrevistas/audio/')),
                ('transcripcion', models.TextField(blank=True, help_text='Transcripción del audio via Whisper')),
                ('puntaje_claridad', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('puntaje_coherencia', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('puntaje_precision', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback_ia', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.entrevistaia')),
            ],
            options={
                'db_table': 'preguntas_entrevista',
                'ordering': ['orden'],
            },
        ),
    ]
