# Generated by Django 4.2.16 on 2026-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_sprint3_schema_evaluaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterField(
            model_name='preguntaexamen',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaexamen',
            name='feedback_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaexamen',
            name='opciones',
            field=models.TextField(blank=True, help_text='JSON serializado: ["A","B","C","D"]. Vacío si es abierta.', null=True),
        ),
        migrations.AlterField(
            model_name='preguntaexamen',
            name='respuesta_candidato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaexamen',
            name='respuesta_correcta',
            field=models.TextField(blank=True, help_text='MC: texto exacto de la opción. Abierta: criterios ideales.', null=True),
        ),
    ]
