# Generated by Django 4.2.16 on 2026-07-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_sprint3_schema_evaluaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Exámenes'},
        ),
    ]
