# Generated by Django 4.2.16 on 2026-07-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_alter_examen_options_alter_preguntaexamen_categoria_and_more'),
        ('evaluaciones', '0004_alter_examen_options'),
    ]

    operations = [
    ]
