# Generated by Django 4.2.16 on 2026-07-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidatos', '0005_candidato_en_banco_talento_candidato_motivo_descarte'),
        ('evaluaciones', '0005_merge_20260704_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrevistaia',
            options={'verbose_name': 'Entrevista IA', 'verbose_name_plural': 'Entrevistas IA'},
        ),
        migrations.AddField(
            model_name='entrevistaia',
            name='analisis_dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrevistaia',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Duración asignada (de la vacante). Techo 40.'),
        ),
        migrations.AddField(
            model_name='entrevistaia',
            name='prompt_utilizado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrevistaia',
            name='resumen_ia',
            field=models.TextField(blank=True, help_text='Resumen ejecutivo de la entrevista para RRHH'),
        ),
        migrations.AddField(
            model_name='entrevistaia',
            name='temas_criticos_cubiertos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='entrevistaia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('expirada', 'Expirada (tiempo agotado)')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PlantillaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_predefinida', models.BooleanField(default=False, help_text='Las 4 base del sistema no se pueden borrar')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de evaluación',
                'verbose_name_plural': 'Plantillas de evaluación',
                'db_table': 'plantillas_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='DimensionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Qué evalúa exactamente esta dimensión (guía para la IA)')),
                ('peso', models.PositiveIntegerField(help_text='Porcentaje 1-100. La suma de la plantilla debe dar 100.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='evaluaciones.plantillaevaluacion')),
            ],
            options={
                'verbose_name': 'Dimensión de evaluación',
                'verbose_name_plural': 'Dimensiones de evaluación',
                'db_table': 'dimensiones_evaluacion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CapturaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('identidad_inicial', 'Foto de identidad (inicio)'), ('periodica', 'Captura periódica')], max_length=25)),
                ('origen', models.CharField(choices=[('examen', 'Durante el examen'), ('entrevista', 'Durante la entrevista')], max_length=15)),
                ('imagen', models.ImageField(upload_to='auditoria/%Y/%m/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas_auditoria', to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Captura de auditoría',
                'db_table': 'capturas_auditoria',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='entrevistaia',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas', to='evaluaciones.plantillaevaluacion'),
        ),
    ]
