# Generated by Django 4.2.16 on 2026-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_plantillas_predefinidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturaauditoria',
            name='es_persona',
            field=models.BooleanField(blank=True, help_text='Validación IA: ¿la captura muestra a una persona? null = sin validar', null=True),
        ),
    ]
