# Generated by Django 4.2.16 on 2026-07-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_capturaauditoria_es_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistaia',
            name='eventos_navegador',
            field=models.JSONField(blank=True, default=list, help_text='Auditoria del navegador durante la entrevista: copiar, cambiar pestana, salir, etc.'),
        ),
    ]
