# Generated by Django 4.2.16 on 2026-05-21 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: VAC-2025-001', max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('tecnologia', 'Tecnología / IT'), ('ventas', 'Ventas / Comercial'), ('marketing', 'Marketing / Digital'), ('rrhh', 'Recursos Humanos'), ('finanzas', 'Finanzas / Contabilidad'), ('legal', 'Legal / Compliance'), ('operaciones', 'Operaciones'), ('atencion_cliente', 'Atención al Cliente'), ('administracion', 'Administración'), ('salud', 'Salud / Medicina'), ('educacion', 'Educación / Docencia'), ('diseno', 'Diseño / UX'), ('produccion', 'Producción / Manufactura'), ('logistica', 'Logística / Supply Chain'), ('investigacion', 'I+D / Investigación'), ('otro', 'Otro')], max_length=30)),
                ('departamento', models.CharField(blank=True, help_text='Departamento interno de la empresa', max_length=100)),
                ('industria', models.CharField(choices=[('software', 'Software / SaaS'), ('banca', 'Banca y Finanzas'), ('retail', 'Retail / Comercio'), ('salud', 'Salud / Farmacia'), ('educacion', 'Educación'), ('manufactura', 'Manufactura / Industrial'), ('servicios', 'Servicios Profesionales'), ('gobierno', 'Gobierno / Sector Público'), ('telecomunicaciones', 'Telecomunicaciones'), ('construccion', 'Construcción / Inmobiliaria'), ('agricultura', 'Agricultura / Agroindustria'), ('ong', 'ONG / Sin fines de lucro'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('descripcion', models.TextField()),
                ('responsabilidades', models.TextField(blank=True)),
                ('requisitos', models.TextField(help_text='Requisitos obligatorios del puesto')),
                ('requisitos_deseables', models.TextField(blank=True, help_text='Requisitos deseables (no excluyentes)')),
                ('habilidades', models.TextField(help_text='Habilidades requeridas separadas por coma')),
                ('tecnologias', models.TextField(blank=True, help_text='Tecnologías/herramientas (puede estar vacío para áreas no técnicas)')),
                ('conocimientos_especificos', models.TextField(blank=True, help_text='Conocimientos teóricos específicos del puesto para el examen IA')),
                ('nivel_experiencia', models.CharField(choices=[('practicante', 'Practicante / Intern'), ('junior', 'Junior (0-2 años)'), ('semi_senior', 'Semi-Senior (2-4 años)'), ('senior', 'Senior (4+ años)'), ('lider', 'Líder / Tech Lead'), ('gerencial', 'Gerencial / C-Level')], default='semi_senior', max_length=20)),
                ('anios_experiencia', models.IntegerField(default=0, help_text='Años mínimos de experiencia')),
                ('nivel_educativo', models.CharField(blank=True, help_text='Ej: Universitario completo, Técnico, Maestría', max_length=100)),
                ('carrera_afin', models.CharField(blank=True, help_text='Carreras afines al puesto', max_length=200)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Contrato indefinido'), ('plazo_fijo', 'Plazo fijo'), ('por_obra', 'Por obra o servicio'), ('practicas', 'Prácticas profesionales'), ('freelance', 'Freelance / Honorarios'), ('part_time', 'Part-time')], default='indefinido', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(default='Lima', max_length=100)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=10)),
                ('mostrar_salario', models.BooleanField(default=False)),
                ('beneficios', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('en_proceso', 'En proceso de selección'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('nota_minima_examen', models.DecimalField(decimal_places=2, default=13.0, help_text='Nota mínima para aprobar el examen teórico (escala 0-20)', max_digits=4)),
                ('top_candidatos_finalistas', models.IntegerField(default=5, help_text='Cantidad de candidatos que pasan a entrevista presencial con RRHH')),
                ('score_cv_minimo', models.IntegerField(default=60, help_text='Score mínimo del CV para avanzar al examen (0-100)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'db_table': 'vacantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
