# Generated by Django 6.0.5 on 2026-05-12 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo', models.CharField(help_text='Código único de la vacante', max_length=20, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('responsabilidades', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('habilidades', models.TextField(help_text='Separadas por comas')),
                ('tecnologias', models.TextField(blank=True, help_text='Separadas por comas')),
                ('idiomas', models.CharField(blank=True, help_text='Ejemplo: Español (nativo), Inglés (intermedio)', max_length=200)),
                ('nivel_experiencia', models.CharField(choices=[('junior', 'Junior (0-2 años)'), ('semi_senior', 'Semi Senior (2-5 años)'), ('senior', 'Senior (5+ años)'), ('lead', 'Tech Lead'), ('manager', 'Manager')], max_length=20)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('practicas', 'Prácticas'), ('freelance', 'Freelance')], default='indefinido', max_length=20)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=10)),
                ('numero_vacantes', models.IntegerField(default=1)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateField(blank=True, help_text='Fecha límite para postular', null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacantes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='vacantes_estado_81bee4_idx'), models.Index(fields=['codigo'], name='vacantes_codigo_260b59_idx')],
            },
        ),
    ]
