# Generated by Django 4.2.16 on 2026-05-21 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='anios_experiencia',
            field=models.IntegerField(default=0, verbose_name='Años mínimos de experiencia'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='beneficios',
            field=models.TextField(blank=True, verbose_name='Beneficios'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='carrera_afin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Carreras afines'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='ciudad',
            field=models.CharField(default='Lima', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='codigo',
            field=models.CharField(editable=False, help_text='Generado automáticamente. Ej: TI-2025-001', max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='conocimientos_especificos',
            field=models.TextField(blank=True, help_text='Temas que la IA debe evaluar en el examen teórico', verbose_name='Conocimientos específicos para examen IA'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='departamento',
            field=models.CharField(blank=True, help_text='Opcional. Ej: Backend, Frontend, Data dentro de TI', max_length=100, verbose_name='Sub-departamento'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del puesto'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('en_proceso', 'En proceso de selección'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='habilidades',
            field=models.TextField(help_text='Separadas por coma. Ej: Java, Spring Boot, MySQL', verbose_name='Habilidades requeridas'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='industria',
            field=models.CharField(choices=[('software', 'Software / SaaS'), ('banca', 'Banca y Finanzas'), ('retail', 'Retail / Comercio'), ('salud', 'Salud / Farmacia'), ('educacion', 'Educación'), ('manufactura', 'Manufactura / Industrial'), ('servicios', 'Servicios Profesionales'), ('gobierno', 'Gobierno / Sector Público'), ('telecomunicaciones', 'Telecomunicaciones'), ('construccion', 'Construcción / Inmobiliaria'), ('agricultura', 'Agricultura / Agroindustria'), ('ong', 'ONG / Sin fines de lucro'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Industria'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='moneda',
            field=models.CharField(default='PEN', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='mostrar_salario',
            field=models.BooleanField(default=False, verbose_name='Mostrar salario al candidato'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel_educativo',
            field=models.CharField(blank=True, help_text='Ej: Universitario completo, Técnico, Maestría', max_length=100, verbose_name='Nivel educativo requerido'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel_experiencia',
            field=models.CharField(choices=[('practicante', 'Practicante / Intern'), ('junior', 'Junior (0-2 años)'), ('semi_senior', 'Semi-Senior (2-4 años)'), ('senior', 'Senior (4+ años)'), ('lider', 'Líder / Tech Lead'), ('gerencial', 'Gerencial / C-Level')], default='semi_senior', max_length=20, verbose_name='Nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nota_minima_examen',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Nota mínima (0-20) para aprobar el examen teórico', max_digits=4, verbose_name='Nota mínima del examen'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='pais',
            field=models.CharField(default='Perú', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos',
            field=models.TextField(verbose_name='Requisitos obligatorios'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos_deseables',
            field=models.TextField(blank=True, verbose_name='Requisitos deseables'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='responsabilidades',
            field=models.TextField(blank=True, verbose_name='Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salario_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario máximo'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salario_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mínimo'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='score_cv_minimo',
            field=models.IntegerField(default=60, help_text='Score mínimo (0-100) para que el candidato avance al examen', verbose_name='Score mínimo de CV'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tecnologias',
            field=models.TextField(blank=True, help_text='Puede estar vacío para áreas no técnicas', verbose_name='Tecnologías / Herramientas'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tipo_contrato',
            field=models.CharField(choices=[('indefinido', 'Contrato indefinido'), ('plazo_fijo', 'Plazo fijo'), ('por_obra', 'Por obra o servicio'), ('practicas', 'Prácticas profesionales'), ('freelance', 'Freelance / Honorarios'), ('part_time', 'Part-time')], default='indefinido', max_length=20, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del puesto'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='top_candidatos_finalistas',
            field=models.IntegerField(default=5, help_text='Cantidad de candidatos que pasan a entrevista presencial con RRHH', verbose_name='Top candidatos finalistas'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección/Ubicación'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del área')),
                ('codigo_corto', models.CharField(help_text='Máximo 10 caracteres, solo letras mayúsculas y números. Ej: TI, VEN, MKT', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Solo letras mayúsculas y números. Sin espacios ni caracteres especiales.', regex='^[A-Z0-9]+$')], verbose_name='Código corto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del área y sus funciones dentro de la empresa', verbose_name='Descripción')),
                ('icono', models.CharField(choices=[('monitor', '💻 Tecnología'), ('trending-up', '📈 Ventas'), ('megaphone', '📣 Marketing'), ('users', '👥 Recursos Humanos'), ('dollar-sign', '💰 Finanzas'), ('briefcase', '⚖️ Legal'), ('settings', '⚙️ Operaciones'), ('headphones', '🎧 Atención al Cliente'), ('clipboard', '📋 Administración'), ('heart', '❤️ Salud'), ('book-open', '📚 Educación'), ('pen-tool', '🎨 Diseño'), ('package', '📦 Producción'), ('truck', '🚚 Logística'), ('flask', '🔬 Investigación'), ('star', '⭐ Otro')], default='star', max_length=30, verbose_name='Ícono')),
                ('color', models.CharField(default='#2E75B6', help_text='Formato hexadecimal. Ej: #2E75B6', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use formato hexadecimal. Ej: #2E75B6', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color (hex)')),
                ('instruccion_ia', models.TextField(blank=True, help_text='Instrucción que la IA usará al generar exámenes y entrevistas para esta área. Si se deja vacío, el sistema usará una instrucción genérica.', verbose_name='Instrucción para IA')),
                ('activa', models.BooleanField(default=True, help_text='Las áreas inactivas no aparecen al crear nuevas vacantes', verbose_name='Activa')),
                ('es_predefinida', models.BooleanField(default=False, help_text='Las áreas predefinidas del sistema no pueden eliminarse', verbose_name='Predefinida por el sistema')),
                ('orden', models.IntegerField(default=0, help_text='Menor número = aparece primero en los listados', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='vacante',
            name='area',
            field=models.ForeignKey(help_text='Área de la empresa a la que pertenece esta vacante', on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='vacantes.area', verbose_name='Área / Departamento'),
        ),
    ]
