# Generated by Django 4.2.16 on 2026-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_alter_vacante_anios_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='icono',
            field=models.CharField(default='star', max_length=50, verbose_name='Ícono'),
        ),
    ]
