# Generated by Django 4.2.16 on 2026-06-01 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0003_area_icono_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='cantidad_posiciones',
            field=models.IntegerField(default=1, help_text='Número de personas a contratar para este perfil'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='confidencial',
            field=models.BooleanField(default=False, help_text='Si está activo: no se publica en canales externos. Solo carga manual y banco de talento.'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha objetivo para cubrir la vacante', null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='horario',
            field=models.CharField(blank=True, help_text='Ej: Lunes a viernes 8am-6pm, Turnos rotativos, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='horario_tipo',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('medio_tiempo', 'Medio tiempo'), ('turnos', 'Turnos rotativos'), ('flexible', 'Horario flexible'), ('por_objetivos', 'Por objetivos')], default='tiempo_completo', max_length=20),
        ),
        migrations.AddField(
            model_name='vacante',
            name='jefe_directo',
            field=models.CharField(blank=True, help_text='Nombre y cargo del jefe directo del puesto', max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='motivo_vacante',
            field=models.CharField(choices=[('nuevo_puesto', 'Nuevo puesto'), ('reemplazo', 'Reemplazo'), ('expansion', 'Expansión del equipo'), ('campana', 'Campaña / Temporal')], default='nuevo_puesto', help_text='¿Por qué se abre esta vacante?', max_length=20),
        ),
        migrations.AddField(
            model_name='vacante',
            name='nombre_reemplazado',
            field=models.CharField(blank=True, help_text='Nombre de la persona que ocupaba el puesto (solo si es reemplazo)', max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='posiciones_cubiertas',
            field=models.IntegerField(default=0, help_text='Cuántas posiciones ya fueron cubiertas'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='solicitante',
            field=models.CharField(blank=True, help_text='Nombre y cargo de quien autorizó abrir la vacante', max_length=200),
        ),
        migrations.AlterField(
            model_name='area',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='codigo_corto',
            field=models.CharField(help_text='Ej: TI, VEN, MKT', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='area',
            name='color',
            field=models.CharField(default='#2E75B6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Formato hex inválido. Ej: #2E75B6')]),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='es_predefinida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='icono',
            field=models.CharField(choices=[('monitor', '💻 Tecnología'), ('trending-up', '📈 Ventas'), ('megaphone', '📣 Marketing'), ('users', '👥 Recursos Humanos'), ('dollar-sign', '💰 Finanzas'), ('briefcase', '⚖️ Legal'), ('settings', '⚙️ Operaciones'), ('headphones', '🎧 Atención al Cliente'), ('clipboard', '📋 Administración'), ('heart', '❤️ Salud'), ('book-open', '📚 Educación'), ('pen-tool', '🎨 Diseño'), ('package', '📦 Producción'), ('truck', '🚚 Logística'), ('flask', '🔬 Investigación'), ('star', '⭐ Otro')], default='star', max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='instruccion_ia',
            field=models.TextField(blank=True, help_text='Instrucción para la IA al analizar CVs y generar preguntas'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='anios_experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='vacantes.area'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='beneficios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='carrera_afin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='ciudad',
            field=models.CharField(default='Lima', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='codigo',
            field=models.CharField(editable=False, help_text='Generado automáticamente. Ej: TI-2025-001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='conocimientos_especificos',
            field=models.TextField(blank=True, help_text='Temas para el examen IA'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='departamento',
            field=models.CharField(blank=True, help_text='Sub-departamento. Ej: Backend dentro de TI', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('en_proceso', 'En proceso de selección'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='habilidades',
            field=models.TextField(help_text='Habilidades requeridas separadas por coma'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='industria',
            field=models.CharField(choices=[('software', 'Software / SaaS'), ('banca', 'Banca y Finanzas'), ('retail', 'Retail / Comercio'), ('salud', 'Salud / Farmacia'), ('educacion', 'Educación'), ('manufactura', 'Manufactura / Industrial'), ('servicios', 'Servicios Profesionales'), ('gobierno', 'Gobierno / Sector Público'), ('telecomunicaciones', 'Telecomunicaciones'), ('construccion', 'Construcción / Inmobiliaria'), ('agricultura', 'Agricultura / Agroindustria'), ('ong', 'ONG / Sin fines de lucro'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='moneda',
            field=models.CharField(default='PEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='mostrar_salario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel_experiencia',
            field=models.CharField(choices=[('practicante', 'Practicante / Intern'), ('junior', 'Junior (0-2 años)'), ('semi_senior', 'Semi-Senior (2-4 años)'), ('senior', 'Senior (4+ años)'), ('lider', 'Líder / Tech Lead'), ('gerencial', 'Gerencial / C-Level')], default='semi_senior', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nota_minima_examen',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='pais',
            field=models.CharField(default='Perú', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos',
            field=models.TextField(help_text='Requisitos obligatorios del puesto'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos_deseables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='responsabilidades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salario_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salario_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='score_cv_minimo',
            field=models.IntegerField(default=60, help_text='Score mínimo del CV para avanzar al examen (0-100)'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tecnologias',
            field=models.TextField(blank=True, help_text='Tecnologías/herramientas'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tipo_contrato',
            field=models.CharField(choices=[('indefinido', 'Contrato indefinido'), ('plazo_fijo', 'Plazo fijo'), ('por_obra', 'Por obra o servicio'), ('practicas', 'Prácticas profesionales'), ('freelance', 'Freelance / Honorarios'), ('part_time', 'Part-time')], default='indefinido', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='top_candidatos_finalistas',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
