# Generated by Django 4.2.16 on 2026-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0006_vacante_publicado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='textos_editados',
            field=models.JSONField(blank=True, default=dict, help_text='Textos de publicación editados manualmente por RRHH. Si está vacío, el sistema genera los textos automáticamente.'),
        ),
    ]
