# Generated by Django 4.2.16 on 2026-07-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_alter_entrevistaia_options_and_more'),
        ('vacantes', '0007_alter_vacante_textos_editados'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='duracion_minutos_entrevista',
            field=models.PositiveIntegerField(default=30, help_text='Duración de la entrevista IA en minutos. Techo del sistema: 40. Sugerencia: practicante 15-20, junior 20-25, mid 25-30, senior 35-40.'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='plantilla_evaluacion',
            field=models.ForeignKey(blank=True, help_text='Plantilla de dimensiones para la entrevista IA. Si es null, se elige automáticamente por área.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes', to='evaluaciones.plantillaevaluacion'),
        ),
    ]
