# Generated by Django 4.2.16 on 2026-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=11)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_usuario', models.EmailField(blank=True, max_length=254)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('score_cv_minimo', models.IntegerField(default=60, help_text='Score mínimo CV para avanzar (0-100)')),
                ('nota_examen_minima', models.DecimalField(decimal_places=2, default=13.0, max_digits=4)),
                ('top_finalistas', models.IntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('reclutador', 'Reclutador'), ('evaluador', 'Evaluador'), ('gerente', 'Gerente')], default='reclutador', max_length=20)),
                ('area_responsable', models.CharField(blank=True, help_text='Área de la empresa que gestiona', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
