# Generated by Django 4.2.16 on 2026-05-21 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet Extranjería'), ('PASSPORT', 'Pasaporte')], default='DNI', max_length=10)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('NI', 'Prefiero no indicar')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('cv', models.FileField(help_text='Archivo PDF del CV', upload_to='cvs/%Y/%m/')),
                ('cv_texto_extraido', models.TextField(blank=True, help_text='Texto extraído del PDF para análisis IA')),
                ('nivel_educativo', models.CharField(blank=True, choices=[('secundaria', 'Secundaria completa'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('bachiller', 'Bachiller'), ('titulado', 'Titulado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('otro', 'Otro')], max_length=20)),
                ('carrera', models.CharField(blank=True, max_length=200)),
                ('universidad', models.CharField(blank=True, max_length=200)),
                ('anios_experiencia', models.IntegerField(default=0)),
                ('cargo_actual', models.CharField(blank=True, max_length=200)),
                ('empresa_actual', models.CharField(blank=True, max_length=200)),
                ('habilidades_declaradas', models.TextField(blank=True, help_text='Habilidades que el candidato declara en su CV')),
                ('cv_analizado', models.BooleanField(default=False)),
                ('fecha_analisis_cv', models.DateTimeField(blank=True, null=True)),
                ('score_cv', models.IntegerField(blank=True, help_text='Score 0-100 del análisis IA', null=True)),
                ('clasificacion_ia', models.CharField(blank=True, choices=[('altamente_recomendado', 'Altamente Recomendado'), ('recomendado', 'Recomendado'), ('requiere_revision', 'Requiere Revisión'), ('no_apto', 'No Apto')], max_length=30)),
                ('resumen_cv', models.TextField(blank=True, help_text='Resumen del CV generado por IA')),
                ('habilidades_detectadas', models.JSONField(default=list, help_text='Habilidades detectadas por IA')),
                ('habilidades_faltantes', models.JSONField(default=list, help_text='Habilidades requeridas no encontradas')),
                ('inconsistencias_cv', models.JSONField(default=list, help_text='Inconsistencias detectadas por IA')),
                ('match_porcentaje', models.IntegerField(blank=True, help_text='% match con requisitos de la vacante', null=True)),
                ('analisis_detallado', models.JSONField(default=dict, help_text='Análisis completo retornado por la IA')),
                ('aprobado_manualmente', models.BooleanField(default=False)),
                ('nota_aprobacion', models.TextField(blank=True)),
                ('score_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('examen_aprobado', models.BooleanField(blank=True, null=True)),
                ('fecha_examen', models.DateTimeField(blank=True, null=True)),
                ('score_entrevista', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dimension_claridad', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dimension_coherencia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dimension_precision', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dimension_comunicacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dimension_seguridad', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback_entrevista', models.TextField(blank=True)),
                ('fecha_entrevista', models.DateTimeField(blank=True, null=True)),
                ('score_final', models.DecimalField(blank=True, decimal_places=2, help_text='Score final: CV×0.25 + Examen×0.40 + Entrevista×0.35', max_digits=5, null=True)),
                ('posicion_ranking', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('postulado', 'Postulado'), ('cv_analizando', 'CV en análisis IA'), ('cv_aprobado', 'CV aprobado'), ('cv_rechazado', 'CV rechazado (score bajo)'), ('examen_pendiente', 'Esperando hacer examen'), ('examen_en_curso', 'Examen en curso'), ('examen_aprobado', 'Examen aprobado'), ('examen_rechazado', 'Examen rechazado (nota baja)'), ('entrevista_pendiente', 'Esperando entrevista IA'), ('entrevista_en_curso', 'Entrevista IA en curso'), ('entrevista_completada', 'Entrevista IA completada'), ('finalista', 'Finalista (top ranking)'), ('entrevista_presencial', 'Entrevista presencial agendada'), ('contratado', 'Contratado'), ('descartado', 'Descartado')], default='postulado', max_length=30)),
                ('es_finalista', models.BooleanField(default=False)),
                ('observaciones_rrhh', models.TextField(blank=True)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_cuenta', models.OneToOneField(blank=True, help_text='Cuenta de acceso del postulante al sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vacantes.vacante')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidatos',
                'ordering': ['-score_final', '-score_cv'],
                'unique_together': {('email', 'vacante')},
            },
        ),
        migrations.CreateModel(
            name='TokenAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('examen', 'Link de acceso al examen'), ('entrevista', 'Link de acceso a la entrevista')], default='examen', max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('ip_uso', models.GenericIPAddressField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Token de acceso',
                'db_table': 'tokens_acceso',
            },
        ),
    ]
