# Generated by Django 6.0.5 on 2026-05-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carné de Extranjería'), ('pasaporte', 'Pasaporte')], default='dni', max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], default='prefiero_no_decir', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('nivel_educacion', models.CharField(choices=[('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('bachiller', 'Bachiller'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='universitario', max_length=20)),
                ('institucion_educativa', models.CharField(blank=True, max_length=200)),
                ('carrera', models.CharField(blank=True, max_length=200)),
                ('años_experiencia', models.IntegerField(default=0, help_text='Años totales de experiencia')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('cv', models.FileField(upload_to='cvs/%Y/%m/')),
                ('carta_presentacion', models.FileField(blank=True, null=True, upload_to='cartas/%Y/%m/')),
                ('fuente', models.CharField(choices=[('linkedin', 'LinkedIn'), ('computrabajo', 'Computrabajo'), ('bumeran', 'Bumeran'), ('referido', 'Referido'), ('web_corporativa', 'Web Corporativa'), ('otro', 'Otro')], default='web_corporativa', max_length=50)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('cv_revisado', 'CV Revisado'), ('en_evaluacion', 'En Evaluación Técnica'), ('evaluado', 'Evaluado'), ('entrevista_ia', 'Entrevista IA'), ('entrevista_rrhh', 'Entrevista RRHH'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('contratado', 'Contratado')], default='registrado', max_length=30)),
                ('cv_analizado', models.BooleanField(default=False)),
                ('resumen_cv', models.TextField(blank=True, help_text='Resumen generado por IA')),
                ('score_cv', models.IntegerField(blank=True, help_text='Puntuación del CV (0-100)', null=True)),
                ('clasificacion_ia', models.CharField(blank=True, choices=[('altamente_recomendado', 'Altamente Recomendado'), ('recomendado', 'Recomendado'), ('requiere_revision', 'Requiere Revisión'), ('no_apto', 'No Apto')], max_length=30)),
                ('observaciones_ia', models.TextField(blank=True)),
                ('score_tecnico', models.IntegerField(blank=True, help_text='Puntuación de prueba técnica (0-100)', null=True)),
                ('fecha_evaluacion_tecnica', models.DateTimeField(blank=True, null=True)),
                ('score_entrevista', models.IntegerField(blank=True, help_text='Puntuación de entrevista IA (0-100)', null=True)),
                ('feedback_entrevista', models.TextField(blank=True)),
                ('fecha_entrevista_ia', models.DateTimeField(blank=True, null=True)),
                ('score_final', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio ponderado de todos los scores', max_digits=5, null=True)),
                ('observaciones_rrhh', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vacantes.vacante')),
            ],
            options={
                'db_table': 'candidatos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['email'], name='candidatos_email_7afd93_idx'), models.Index(fields=['numero_documento'], name='candidatos_numero__f4d91e_idx'), models.Index(fields=['vacante', 'estado'], name='candidatos_vacante_4287f4_idx')],
            },
        ),
    ]
