# Generated by Django 4.2.16 on 2026-06-01 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenacceso',
            options={},
        ),
        migrations.AddField(
            model_name='candidato',
            name='acepta_ciudad',
            field=models.BooleanField(blank=True, help_text='¿El candidato acepta trabajar en la ciudad del puesto?', null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='acepta_modalidad',
            field=models.BooleanField(blank=True, help_text='¿El candidato acepta la modalidad del puesto?', null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='disponibilidad',
            field=models.CharField(blank=True, help_text='Ej: Inmediata, 30 días de preaviso, A partir de enero 2026', max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pretension_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pretensión salarial mensual en la moneda del puesto', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='source',
            field=models.CharField(choices=[('manual', 'Carga manual por RRHH'), ('carga_masiva', 'Carga masiva'), ('formulario', 'Formulario público'), ('buzon_imap', 'Buzón de correo automático'), ('referido', 'Referido interno'), ('linkedin', 'LinkedIn'), ('computrabajo', 'Computrabajo'), ('bumeran', 'Bumeran'), ('indeed', 'Indeed'), ('otro_portal', 'Otro portal')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='analisis_detallado',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cv',
            field=models.FileField(upload_to='cvs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cv_texto_extraido',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_postulacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 1, 6, 41, 27, 473601, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilidades_declaradas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilidades_detectadas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilidades_faltantes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='inconsistencias_cv',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='match_porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='resumen_cv',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='score_cv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='score_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='usuario_cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6B7280', help_text='Color hex. Ej: #6B7280', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'tags',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NotaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_candidatos', to=settings.AUTH_USER_MODEL)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Nota de candidato',
                'db_table': 'notas_candidatos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='candidatos', to='candidatos.tag'),
        ),
    ]
