# Generated by Django 4.2.16 on 2026-06-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_tokenacceso_options_candidato_acepta_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenacceso',
            name='codigo_corto',
            field=models.CharField(blank=True, help_text='Código legible para ingresar en la app móvil', max_length=20, null=True, unique=True),
        ),
    ]
