# Generated by Django 4.2.16 on 2026-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_tokenacceso_codigo_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
