# Generated by Django 4.2.16 on 2026-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_alter_candidato_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='en_banco_talento',
            field=models.BooleanField(default=False, help_text='Candidato valioso guardado para futuras vacantes'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='motivo_descarte',
            field=models.TextField(blank=True, help_text='Razón registrada al descartar al candidato'),
        ),
    ]
