# Generated by Django 4.2.16 on 2026-07-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_candidato_en_banco_talento_candidato_motivo_descarte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('riesgo_examen', 'Examen con riesgo alto'), ('entrevista_lista', 'Entrevista completada'), ('general', 'General')], default='general', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('leida', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='candidatos.candidato')),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-creada'],
            },
        ),
    ]
